/// <reference types="next" />
/// <reference types="next/types/global" />
/// <reference types="next/image-types/global" />

// NOTE: This file should be automatically generated by Next.js.
// If you see type errors about JSX, ensure `@types/react` is installed and restart TS server.
